
export const tasks = [
  {
    id: 1,
    title: "Design Landing Page",
    description: "Create a responsive landing page for the new product launch.",
    status: "In Progress",
    priority: "High Priority",
    taskDone: 3,
    taskTotal: 5,
    startDate: "2026-03-20",
    dueDate: "2026-03-30",
  },
  {
    id: 2,
    title: "Fix Login Bug",
    description: "Resolve the login error affecting some users on mobile devices.",
    status: "Pending",
    priority: "Medium Priority",
    taskDone: 0,
    taskTotal: 1,
    startDate: "2026-03-22",
    dueDate: "2026-03-28",
  },
  {
    id: 3,
    title: "Write Blog Post",
    description: "Draft a 1500-word blog post about upcoming features in our app.",
    status: "Completed",
    priority: "Low Priority",
    taskDone: 1,
    taskTotal: 1,
    startDate: "2026-03-18",
    dueDate: "2026-03-23",
  },
  {
    id: 4,
    title: "Update User Dashboard",
    description: "Redesign dashboard with new analytics widgets and charts.",
    status: "In Progress",
    priority: "Medium Priority",
    taskDone: 2,
    taskTotal: 4,
    startDate: "2026-03-19",
    dueDate: "2026-04-01",
  },
  {
    id: 5,
    title: "QA Testing for Mobile App",
    description: "Test the mobile application for iOS and Android devices.",
    status: "Pending",
    priority: "High Priority",
    taskDone: 0,
    taskTotal: 3,
    startDate: "2026-03-21",
    dueDate: "2026-03-29",
  },
];

export const filters = [
  { label: "All", count: tasks.length },
  { label: "Pending", count: tasks.filter((t) => t.status === "Pending").length },
  { label: "In Progress", count: tasks.filter((t) => t.status === "In Progress").length },
  { label: "Completed", count: tasks.filter((t) => t.status === "Completed").length },
];